### ISSUE TITLE
Issue with UpdateUserMetadata

### ISSUE THREAD

**Issue by krishnadubagunta** [clerk/clerk-sdk-go#216] opened 2024-02-05 15:33 UTC
I found this issue similar to what I was facing. https://github.com/clerk/clerk-sdk-go/issues/109 

I couldn't update the metadata, it fails on awaiting headers for some reason.  I made sure my keys are current, and are passing into the request. Here what I get, 

```
Patch "https://api.clerk.dev/v1/users/<userId>/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

For this code

```go
updatedMetadata := map[string]string{
	"artist_id": strconv.FormatInt(ar.ID, 10),
	"role":      ar.Role,
}
mar, _ = json.Marshal(updatedMetadata)
retry := 5
for i := 0; i < retry; i++ {
	// err := updateUserMetadata(webhookArtist.Data.ID, mar)
	user, err := client.Users().UpdateMetadata(webhookArtist.Data.ID, &clerk.UpdateUserMetadata{
		PublicMetadata: mar,
	})
	if err != nil {
		log.Println(err)
		i += 1
	} else {
		log.Println("Worked ", user)
		break
	}
}
```
and when I give the same data into the http request, it updates metadata, like so
```go
url := fmt.Sprintf("https://api.clerk.dev/v1/users/%s/metadata", userID)
method := "PATCH"

payload := map[string]interface{}{
	"public_metadata": message,
}

j, err := json.Marshal(payload)
if err != nil {
	return err
}

client := &http.Client{}

req, err := http.NewRequest(method, url, bytes.NewReader(j))
if err != nil {
	return err
}

req.Header.Add("Authorization", fmt.Sprintf("Bearer %s", "token"))
req.Header.Add("Content-Type", "application/json")

res, err := client.Do(req)
if err != nil {
	return err
}

return res.Body.Close()
```
Is there something that I'm missing?

**Comment by gkats** [comment] 2024-02-05 15:42
Hello @krishnadubagunta thanks for reporting the issue.

Is the problem happening constantly? The error message suggests that it might be a temporary issue.

**Comment by krishnadubagunta** [comment] 2024-02-05 16:05
@gkats I've only began to use clerk 3 days ago, and this is constantly happening.

**Comment by gkats** [comment] 2024-02-05 16:14
> I've only began to use clerk 3 days ago, and this is constantly happening.

Thanks for the reply. Seems to be a bigger problem then. We'll look into it.

**Comment by krishnadubagunta** [comment] 2024-02-05 16:18
> > I've only began to use clerk 3 days ago, and this is constantly happening.
> 
> Thanks for the reply. Seems to be a bigger problem then. We'll look into it.

Let me know if you need any help, I'm on IST, so my reply might be delayed, apologies in advance.

**Comment by krishnadubagunta** [comment] 2024-02-05 21:08
@gkats  This is also related, I'm not able to make any requests. 

how I'm using inject session: 
```go
routes.ApiRoutes(e.Group("/api", echo.WrapMiddleware(injectSession), middlewares.SessionMiddleware))
```

I'm getting a similar error as above and this is when verifying jwt token from header, and is also consistent.


```sh
Get "https://api.clerk.dev/v1/jwks": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by krishnadubagunta** [comment] 2024-02-05 21:35
Ok I was able to get the request working. looks like JWKs API needs a token to execute, and a token was not send in the request header. 

https://github.com/clerk/clerk-sdk-go/blob/8bd66b16f28be05ad4377d3f24d2ace2c65d5fb3/clerk/jwks.go#L13

here, this should be 

```go
func (s *JWKSService) ListAll(token string) (*JWKS, error) {
	req, _ := s.client.NewRequest(http.MethodGet, "jwks", nil)
        req.Header.Add("Authorization", "Bearer "+token)
}
```
to properly execute the request. If you think this is fine, I can submit a PR.

**Comment by krishnadubagunta** [comment] 2024-02-06 09:29
@gkats I might be bugging you too frequently, but my work is stopped because of the issue. 

Found this
https://github.com/clerk/clerk-sdk-go/blob/8bd66b16f28be05ad4377d3f24d2ace2c65d5fb3/clerk/clerk.go#L110-L116

Does the token in the params mean API token? or the JWT? If this is API token, why should this not be used across all users? since this is going to be used in the backend to interact with Clerk, IMO this should be used for all users. I think I didn't understand `users` here. 

and then here
https://github.com/clerk/clerk-sdk-go/blob/8bd66b16f28be05ad4377d3f24d2ace2c65d5fb3/clerk/clerk.go#L217-L221

We give c.token as the Bearer token, which expects JWT, and not the API token itself, according to docs on clerk https://clerk.com/docs/reference/backend-api/tag/JWKS#operation/GetJWKS

**Comment by gkats** [comment] 2024-02-06 17:41
Hey @krishnadubagunta I tried to reproduce the problem earlier today but unfortunately it worked as expected.

Here's the code I'm using
```go
func main() {
	apiKey := "sk_test_XXXX"
	client, err := clerk.NewClient(apiKey)
	if err != nil {
		panic(err)
	}
	usersService := client.Users()

	users, err := usersService.ListAll(clerk.ListAllUsersParams{})
	if err != nil {
		panic(err)
	}
	if len(users) < 1 {
		panic(fmt.Errorf("no users"))
	}

	raw := `{"foo": "bar"}`
	user := users[0]
	
	// I also tried adding this in a loop as per your original example
	// for i := 0; i < 5; i++ {
	updated, err := usersService.UpdateMetadata(user.ID, &clerk.UpdateUserMetadata{
		PublicMetadata: json.RawMessage(raw),
	})
	if err != nil {
		log.Println(err)
	} else {
	        log.Println("updated", updated.PublicMetadata)
	}
}
```

The fact that you had to increase the http.Client timeout indicates that this is probably a network related error. I admit that a 5 second timeout might be a bit small though.

By the way, you can specify your own http.Client when instantiating the clerk.Client.
```go
client, err := clerk.NewClient(apiKey, clerk.WithHTTPClient(&http.Client{
  Timeout: 5 * time.Second, // set this to whatever you prefer
})
```
See [here](https://github.com/clerk/clerk-sdk-go/blob/8bd66b16f28be05ad4377d3f24d2ace2c65d5fb3/README.md#options) for another example.

I'll close this issue for now. Feel free to reopen if the problem happens again or the solution does not work for you.

**Closed by gkats** 2024-02-06 17:41 UTC
