### ISSUE TITLE
UpdateMetadata appears to fail silently.

### ISSUE THREAD

**Issue by bnewland123** [clerk/clerk-sdk-go#272] opened 2024-03-01 17:59 UTC
I'm testing updating user metadata with the SDK. The call appears to succeed with no error, but the user is not updated.
Is there something else that I'm missing here? I've also made sure the ID is the correct one.

```go
privateStuff := map[string]interface{}{
	"pid": "<id>",
}
publicStuff := map[string]interface{}{
	"likes": "videogames",
}
unsafe := make(map[string]interface{})
privateBytes, err := json.Marshal(privateStuff)
if err != nil {
	log.Error(err)
	return nil, err
}
publicBytes, err := json.Marshal(publicStuff)
if err != nil {
	log.Error(err)
	return nil, err
}
unsafeBytes, err := json.Marshal(unsafe)
if err != nil {
	log.Error(err)
	return nil, err
}
log.Infof("Updating user with ID: %s", user.ID)
updatedUser, err := client.Users().UpdateMetadata(user.ID, &clerk.UpdateUserMetadata{
	PrivateMetadata: privateBytes,
	PublicMetadata:  publicBytes,
	UnsafeMetadata:  unsafeBytes,
})
```

**Comment by gkats** [comment] 2024-03-02 14:35
Thanks for reporting @bnewland123. This is indeed a bug.

The issue is fixed in the v2 version of the Go SDK. https://github.com/clerk/clerk-sdk-go/tree/v2

We'll take a look into the problem and try to fix it for v1 as well.

**Comment by reginaldl** [comment] 2024-03-15 19:44
@gkats I have the same problem with v2:
```        data, err := json.Marshal(publicMetadata)
        if err != nil {
                return err 
        }   
        rawMessage := json.RawMessage(data)
        u, err := user.UpdateMetadata(
                context.Background(),
                userId,
                &user.UpdateMetadataParams{
                        PublicMetadata: &rawMessage,
                },  
        )   
        log.Printf("%v", string(u.Response.RawJSON))
        return err 
```
Same behavior as described earlier, succeeds but won't update. Switching to `user.Update` works though.

**Comment by reginaldl** [comment] 2024-03-15 21:13
So it turns out to be a backend issue and `X-Clerk-Sdk` header, I can repro with the following curl command:
```
curl -vvv -X PATCH 'https://api.clerk.com/v1/users/<user_id>/metadata' \
-H 'Authorization: Bearer <secret>' \
-H 'Content-Type: application/json' \
-H 'User-Agent: clerk/clerk-sdk-go@v2.0.0' \
-H 'X-Clerk-Sdk: go/v2.0.0' \
-d '{"public_metadata":{"test":"ok"}}'
```

This won't work. Remove `X-Clerk-Sdk` header and it works.

**Comment by gkats** [comment] 2024-03-19 10:59
Hello @reginaldl thank you for reporting. This was indeed a backend issue as you found out yourself. 

The fix is now live.

> Also, is v2 still in beta?

Yes, v2 is still in beta, at least officially. It's pretty stable though and we don't expect the APIs to change. The only thing that's missing is cookie-based authentication support.

**Comment by reginaldl** [comment] 2024-03-19 17:04
Great! Thanks for the update. Let's close this ticket.

**Comment by pedro-sharpi** [comment] 2024-08-29 18:29
I'm facing the same issue in the v2 sdk. Any solutions?

**Comment by gkats** [comment] 2024-09-10 06:42
Hello @pedro-sharpi, can you provide more details on the issue you're facing with v2?

I can run the following snippet successfully. All the different types of metadata for the user get updated correctly.

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/clerk/clerk-sdk-go/v2"
	"github.com/clerk/clerk-sdk-go/v2/user"
)

func main() {
	clerk.SetKey("sk_XXXXXXXXXXXXXXXXXXXXXXXXXX")

	ctx := context.Background()
	email := []string{"test1@example.com"}
	usr, err := user.Create(ctx, &user.CreateParams{
		EmailAddresses: &email,
		Password:       clerk.String("nOtS3curE"),
	})
	if err != nil {
		panic(err)
	}

	metadata := json.RawMessage(`{"test":"ok"}`)
	usr, err = user.UpdateMetadata(ctx, usr.ID, &user.UpdateMetadataParams{
		PublicMetadata:  &metadata,
		UnsafeMetadata:  &metadata,
		PrivateMetadata: &metadata,
	})
	fmt.Println(string(usr.PublicMetadata), string(usr.UnsafeMetadata), string(usr.PrivateMetadata))
}
```

I'll close this issue for now, but feel free to reopen if there's still a problem. Thanks!

**Closed by gkats** 2024-09-10 06:42 UTC
